name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Current Date insertion
      id: date
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sridhanush1307/hello_world:${{ steps.date.outputs.date }}
    - name: docker push
      run: |
        docker push sridhanush1307/hello_world:${{ steps.date.outputs.date }}
